### PR TITLE
fix: update index.d.ts

### LINKED ISSUE #85: TypeScript issues with Electron 15.x and 2.0.1
Receiving build errors in my electron project.  It appears as though there are errors in the types files between the native electron resources and this expansion lib mappings.  Anyone else seeing this issue, or any guidance on correcting the issue?

(ex1)
```
Error: node_modules/@electron/remote/index.d.ts:8:43 - error TS2339: Property 'ClientRequest' does not 
exist on type 'typeof CrossProcessExports'.

8 export var ClientRequest: typeof Electron.ClientRequest;
```

(ex2)
```
Error: node_modules/@electron/remote/index.d.ts:10:41 - error TS2339: Property 'CommandLine' does not
 exist on type 'typeof CrossProcessExports'.

10 export var CommandLine: typeof Electron.CommandLine;
```

### PR DESCRIPTION
**Pull request by oskCom**
Fix #85 #101 

I referred to #94

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -1,30 +1,30 @@
 import * as Electron from 'electron';
-
+import * as Main from 'electron/main'
 // Taken from `RemoteMainInterface`
 export var app: Electron.App;
 export var autoUpdater: Electron.AutoUpdater;
 export var BrowserView: typeof Electron.BrowserView;
 export var BrowserWindow: typeof Electron.BrowserWindow;
```
Comment (nornagon) [inline index.d.ts:7]: Confused why not update all of these?

```suggestion
export var BrowserView: Main.BrowserView;
export var BrowserWindow: Main.BrowserWindow;
```

etc.

Comment (oskCom) [reply index.d.ts:7]: Thank you for your review.

I tried.
> export var BrowserWindow: Main.BrowserWindow;

However, an error occurs because the static member of BrowserWindow cannot be referenced.


code&error
```
import * as _remote from '@electron/remote';
_remote.BrowserWindow.getAllWindows();
                      ~~~~~~~~~~~~~~~
                      ^ Property 'getAllWindows' is a static member of type 'BrowserWindow'.

```
